import Head from 'next/head';

import Header from "../components/Header"
import NoteCard from "../components/NoteCard"
import Footer from "../components/Footer"


export default function Home() {

  return (
    <>
      <Head>
        <title>Falcon Ace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <NoteCard/>
      <Footer/>
    </>

  )
}
